plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

group = mod_group_id
version = mod_version + "+build" + mod_build_number

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel") // BlockBench project files
    exclude("src/generated/**/.cache") // datagen cache files
}

repositories {
    mavenLocal()
    flatDir {
        dir 'libs'
    }
    maven { // TOP
        url "https://cursemaven.com"
    }
    maven { //mirror
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }
    maven {
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        url "https://maven.blamejared.com"
    }
    maven {
        url = "https://maven.enjarai.dev/mirrors"
    }
}

base {
    archivesName = mod_id
}

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client1 {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = project.file('./run/client1')
            programArguments.addAll("--username", "player1")
        }

        client2 {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            gameDirectory = project.file('./run/client2')
            programArguments.addAll("--username", "player2")
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom(localRuntime)
    compileClasspath.extendsFrom(localCompile)

    runtimeClasspath.extendsFrom(localImpl)
    compileClasspath.extendsFrom(localImpl)
}

dependencies {
    //Patchouli
    localImpl "vazkii.patchouli:Patchouli:1.21.1-93-NEOFORGE"

    //JEI
    localImpl "curse.maven:jei-238222:7420587"

    //player animator
    localImpl "dev.kosmx.player-anim:player-animation-lib-forge:2.0.1+1.21.1"
    localImpl "io.github.kosmx.bendy-lib:bendy-lib-forge:5.1"

    if(!project.gradle.startParameter.taskNames.any { "runServer" in it }) {
        localRuntime "curse.maven:freecam-by-zergatul-618947:5591136"
        localRuntime "curse.maven:jade-324717:7545219"
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_credits            : mod_credits,
            mod_url                : mod_url,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.addStringOption('Xdoclint:-missing', '-quiet')
    options.encoding = 'UTF-8'
    failOnError = false
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from(components.java)
            artifactId = mod_id
        }
    }
    repositories {
        mavenLocal()
        maven {
            name = 'LTDNexus'
            url = 'https://nexus.bot.leisuretimedock.top/repository/maven-releases/'
            credentials {
                username = System.getenv('LTDNexusUsername') ?: ''
                password = System.getenv('LTDNexusPassword') ?: ''
            }
        }
        maven {
            name = 'MafuyuNexus'
            url = 'https://maven.sighs.cc/repository/maven-releases/'
            credentials {
                username = System.getenv('MafuyuNexusUsername') ?: ''
                password = System.getenv('MafuyuNexusPassword') ?: ''
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}